kind: pipeline
type: kubernetes
name: deploy
platform:
    arch: amd64
steps:

    - name: deploy to kubernetes
      image: alpine/helm:3.5.4
      volumes:
        - factorio_folder:/factorio_data
      environment:
        KUBECONFIG_VAL:
          from_secret: kubeconfig
      commands:
        - mkdir /root/.kube
        - echo $KUBECONFIG_VAL | base64 -d > /root/.kube/config
        - helm delete factorio
        - rm -rf /factorio_data/*
        - cp -r ./factorio_data/* /factorio_data/
        - helm --kubeconfig /root/.kube/config install factorio ./factorio_server
volumes:
    - name: factorio_folder
      driver_opts:
        type: nfs
        o: addr=nas.hnatekmar.xyz,rw
        device: ":/factorio"
      
