{{ define "appName" }}
  {{- printf "%s-factorio" .Chart.Name -}}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "appName" . }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "appName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "appName" . }}
  template:
    metadata:
      labels:
        app: {{ template "appName" . }}
    spec:
      containers:
      - name: factorio
        image: {{ .Values.image.repository }}
        ports:
          - containerPort: 34197
            hostPort: 34197
            protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "appName" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  loadBalancerIP: 192.168.1.100
  type: LoadBalancer
  selector:
    app: {{ template "appName" . }}
  ports:
    - port: 34197
      protocol: UDP
      name: server
      targetPort: 34197
